import 'package:xapptor_translation/model/text_list.dart';

TranslationTextListArray text_list = TranslationTextListArray(
  [
    TranslationTextList(
      source_language: "en",
      text_list: [
        "Enter the initial day of your reservation",
        "Enter the last day of your reservation",
        "Reservation Period",
        "Cabin",
        "Price",
        "Capacity",
        "People",
        "Description",
        "Bed",
        "Bathrooms",
        "Kitchen",
        "Sauna",
        "Livingroom",
        "Chimney",
        "Balcony",
        "Yes",
        "No",
        "Ideal for big families or groups of friends.",
        "Ideal for families or groups of friends.",
        "Ideal for couples.",
        "Confirm",
        "Confirm Reservation",
        "Cancel",
        "Ok",
        "New Reservation",
        "Reservations",
        "You don't have any active reservations",
        "Confirm deletion",
        "Username",
        "Delete",
        "Edit",
        "Add Payment",
        "Amount",
        "Total",
        "Paid",
        "MXN",
        "/Per Night",
      ],
    ),
    TranslationTextList(
      source_language: "es",
      text_list: [
        "Selecciona el día inicial de tu reservación",
        "Selecciona el último día de tu reservación",
        "Periodo de Reservación",
        "Cabaña",
        "Precio",
        "Capacidad",
        "Personas",
        "Descripción",
        "Camas",
        "Baños",
        "Cocina",
        "Sauna",
        "Sala",
        "Chimenea",
        "Balcón",
        "Si",
        "No",
        "Ideal para familias y grupos de amigos grandes.",
        "Ideal para familias y grupos de amigos.",
        "Ideal para parejas.",
        "Confirmar",
        "Confirmar Reservación",
        "Cancelar",
        "Ok",
        "Nueva Reservación",
        "Reservaciones",
        "No posees ninguna reservación activa",
        "Confirmar la eliminación",
        "Nombre de Usuario",
        "Eliminar",
        "Editar",
        "Agregar Pago",
        "Cantidad",
        "Total",
        "Pagado",
        "MXN",
        "/Por Noche",
      ],
    ),
  ],
);
